name: Cover App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: Run unit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          args: --coverage-text
